#ifndef _SMARTRF_SETTINGS_H_
#define _SMARTRF_SETTINGS_H_


//*********************************************************************************
// Generated by SmartRF Studio version 2.11.0 (build #122)
// Tested for SimpleLink SDK version: CC13x0 SDK 2.30.xx.xx
// Device: CC1310 Rev. 2.1
//
//*********************************************************************************

#include <devices/cc13x0/driverlib/rf_mailbox.h>
#include <devices/cc13x0/driverlib/rf_common_cmd.h>
#include <devices/cc13x0/driverlib/rf_prop_cmd.h>

#include <drivers/rf/RF.h>

// TI-RTOS RF Mode Object
extern RF_Mode RF_prop; //we shouldnt need this

// RF Core API commands
extern rfc_CMD_PROP_RADIO_DIV_SETUP_t RF_cmdPropRadioDivSetup; //will put us in the sub 1-Ghz band
extern rfc_CMD_FS_t RF_cmdFs; //will set synthesizer freq
extern rfc_CMD_PROP_TX_t RF_cmdPropTx; //will send 1 packet in proprietary mode (simple format)
extern rfc_CMD_PROP_RX_t RF_cmdPropRx; //will receive 1 or more packets in proprietary mode (simple format)
extern rfc_CMD_TX_TEST_t RF_cmdTxTest; //will send modulated or unmodulated test signal

// RF Core API Overrides
extern uint32_t pOverrides[];

#endif // _SMARTRF_SETTINGS_H_
