#!/bin/bash
WIDTH=1056
HEIGHT=816
for ((i = 0; i < 3; i++))
do 
	for ((j = 0; j < 3; j++))
	do
		echo ${i}_${j}
		inkscape --export-filename=${i}_${j}_$2.png \
				 --export-area=$((i*WIDTH)):$((j*HEIGHT)):$(((i+1)*WIDTH)):$(((j+1)*HEIGHT)) \
				 $1
	done

done

mv *_*_$2.png $3
